### ISSUE TITLE
Sysmon does not build with haskell 8.0: constructor ‘DataD’ should have 6 arguments, but has been given 5

### ISSUE THREAD

**Issue by juharov** [rukav/Sysmon#1]
See also https://github.com/haskell-CI/hackage-matrix-builder/issues/32
package Sysmon does not build.
OS: Ubuntu 18.04.1 LTS
Haskell: 8.0.2

$ runhaskell Setup.hs build
Building Sysmon-0.1.2...
Preprocessing library Sysmon-0.1.2...
[3 of 8] Compiling Database.Sybase.Sysmon.Average ( src/Database/Sybase/Sysmon/Average.hs, dist/build/Database/Sybase/Sysmon/Average.o )

src/Database/Sybase/Sysmon/Average.hs:29:10: error:
• Illegal instance declaration for ‘Averageable String’
(All instance types must be of the form (T a1 ... an)
where a1 ... an are distinct type variables,
and each type variable appears at most once in the instance head.
Use FlexibleInstances if you want to disable this.)
• In the instance declaration for ‘Averageable String’

src/Database/Sybase/Sysmon/Average.hs:33:10: error:
• Illegal instance declaration for ‘Averageable LogInterval’
(All instance types must be of the form (T a1 ... an)
where a1 ... an are distinct type variables,
and each type variable appears at most once in the instance head.
Use FlexibleInstances if you want to disable this.)
• In the instance declaration for ‘Averageable LogInterval’

=> Adding "{-# LANGUAGE FlexibleInstances #-}" to the top of Average.hs

$ runhaskell Setup.hs build
Building Sysmon-0.1.2...
Preprocessing library Sysmon-0.1.2...
[3 of 8] Compiling Database.Sybase.Sysmon.Average ( src/Database/Sybase/Sysmon/Average.hs, dist/build/Database/Sybase/Sysmon/Average.o )
[4 of 8] Compiling Database.Sybase.Sysmon.Derive ( src/Database/Sybase/Sysmon/Derive.hs, dist/build/Database/Sybase/Sysmon/Derive.o )

src/Database/Sybase/Sysmon/Derive.hs:23:11: error:
• The constructor ‘DataD’ should have 6 arguments, but has been given 5
• In the pattern: DataD _ _ _ constructors _
In the pattern: TyConI (DataD _ _ _ constructors _)
In a stmt of a 'do' block:
TyConI (DataD _ _ _ constructors _) <- reify t
